# Generated by Django 5.0.1 on 2024-06-17 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0012_alter_message_open_room"),
    ]

    operations = [
        migrations.AlterField(
            model_name="open_room",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="room",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
